#!/bin/env bash
import setColour
import log
function setMenuSize(){
local HEIGHT=$(($(tput lines) - 5))
local WIDTH=$(($(tput cols) - 5))
local OPTION=$((${HEIGHT} - 7))
if (( $HEIGHT <= 3 ));then
  log.error "您的屏幕高度过低"
  log.warn "考虑缩小终端字体"
  exit
fi
if (( $WIDTH <= 0 ));then  
  log.error "您的屏幕宽度过窄"
  log.warn "考虑缩小终端字体"
  exit
fi
echo ${HEIGHT} ${WIDTH} ${OPTION}
}
