#!/bin/env bash
import setColour
import log
function setMsgboxSize(){
local HEIGHT=$(($(tput lines) - 15))
local WIDTH=$(($(tput cols) - 5))
if (( $HEIGHT <= 0 ));then
  log.error "您的屏幕高度过低"
  log.warn "考虑缩小终端字体"
  exit
fi
if (( $WIDTH <= 0 ));then
  log.error "您的屏幕宽度过窄"
  log.warn "考虑缩小终端字体"
  exit
fi
echo ${HEIGHT} ${WIDTH}
}