#!/bin/env bash
Path=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source ${Path}/../../Function/import
source ${Path}/getAppMode

import setMsgboxSize
import setTUISoftware
import manageSession

getAppMode "$SN" "$SC"
case $? in
  1)
    manageSession "$TM" log "$SN"
    ;;
  2)
    $(setTUISoftware) --title "$TT"  \
    --msgbox "$SN 目前处于 [前台]" \
    $(setMsgboxSize)
    ;;
  0)
    $(setTUISoftware) --title "$TT"  \
    --msgbox "$SN 目前处于 [未启动]" \
    $(setMsgboxSize)
    ;;
esac
